"""add is_manager to person

Revision ID: 19086e35f07b
Revises: 3560ca6982d2
Create Date: 2026-09-22 12:13:10.985005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19086e35f07b'
down_revision = '3560ca6982d2'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manager', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('is_manager')

    # ### end Alembic commands ###
