"""Add dues table

Revision ID: 70831da659b6
Revises: e4e38c3c0b7b
Create Date: 2026-09-02 13:59:48.311671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70831da659b6'
down_revision = 'e4e38c3c0b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'year', 'month', name='uq_due_unit_year_month')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dues')
    # ### end Alembic commands ###
