"""Replace gross area with block name

Revision ID: f1044896aea2
Revises: 7c140e8926b8
Create Date: 2026-08-31 02:34:13.625156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1044896aea2'
down_revision = '7c140e8926b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('gross_area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gross_area', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.drop_column('block_name')

    # ### end Alembic commands ###
